repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/rubik/xenon
  rev: v0.9.1
  hooks:
  - id: xenon