#Add Other Tests

.PHONY: all

all: Equipment Abilities Armor Stats Roles

Equipment:
	make -C Equipment

Roles:
	make -C Roles

Abilities:
	make -C Abilities

Armor:
	make -C Armor

Stats:
	make -C Stats