.PHONY: all clean

all: 
	make -C Equipment all
	make -C Roles all
	make -C Abilities all
	make -C Armor all
	make -C Stats all

clean:
	make -C Equipment clean
	make -C Roles clean
	make -C Abilities clean
	make -C Armor clean
	make -C Stats clean