
all	:	EquipmentTest

EquipmentTest	:	CodeTest_Equipment.o
							g++ -o EquipmentTest.exe CodeTest_Equipment.o

CodeTest_Equipment.o	:	CodeTest_Equipment.cpp
							g++ -I ./ -c CodeTest_Equipment.cpp